### ISSUE TITLE
Jetpack error after theme activation

### ISSUE THREAD

**Issue by marpa** [clas-web/translucence-transition#3]
After the variations template theme is activated there is the following error:
Fatal error: Class 'Jetpack_Custom_CSS' not found in /home/pages/public_html/wp-content/plugins/translucence-transition/main-transition.php on line 96

**Comment by atrus1701** [comment]
fixed on production.

**Comment by atrus1701** [comment]
b61d4cc56d4004b5b6d283ea421b0c4dd4506f23
