### ISSUE TITLE
Title box position incorrect after transition

### ISSUE THREAD

**Issue by marpa** [clas-web/translucence-transition#4]
When the theme is changed from Translucence to Variation Template, the title-box position is set to "hleft vbottom" when it should be "hleft vtop"

**Comment by atrus1701** [comment]
bug in translucence transition that was fixed on production server.

**Comment by atrus1701** [comment]
Forgot a break statement in the switch.  Fixed in commit:
066548b3700e1bb95bd44d80c68c9764ea14ba61
